<?php 

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
    'key' => 'group_modularity_folder_browser_instance',
    'title' => __('Inställningar för mappbläddrare', 'modularity-folder-browser'),
    'fields' => array(
        0 => array(
            'key' => 'field_modularity_folder_browser_top_folder_name',
            'label' => __('Namn på toppmapp', 'modularity-folder-browser'),
            'name' => 'top_folder_name',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => __('Valfri mappetikett som omsluter de valda mapparna på webbplatsen.', 'modularity-folder-browser'),
            'required' => 0,
            'conditional_logic' => false,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => __('Lämna tomt för att visa valda mappar direkt', 'modularity-folder-browser'),
            'maxlength' => '',
            'prepend' => '',
            'append' => '',
        ),
        1 => array(
            'key' => 'field_modularity_folder_browser_start_folders',
            'label' => __('Startmappar', 'modularity-folder-browser'),
            'name' => 'start_folders',
            'aria-label' => '',
            'type' => 'repeater',
            'instructions' => __('Välj en eller flera mappar i konfigurerade filsystemskällor. Absoluta sökvägar sparas aldrig.', 'modularity-folder-browser'),
            'required' => 1,
            'conditional_logic' => false,
            'wrapper' => array(
                'width' => '',
                'class' => 'mod-file-browser-start-folders-field',
                'id' => '',
            ),
            'layout' => 'block',
            'button_label' => __('Lägg till mapp', 'modularity-folder-browser'),
            'min' => 1,
            'max' => 0,
            'rows_per_page' => 20,
            'collapsed' => '',
            'acfe_repeater_stylised_button' => 0,
            'sub_fields' => array(
                0 => array(
                    'key' => 'field_modularity_folder_browser_source',
                    'label' => __('Rotmapp', 'modularity-folder-browser'),
                    'name' => 'source',
                    'aria-label' => '',
                    'type' => 'select',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '100',
                        'class' => 'mod-file-browser-source-field',
                        'id' => '',
                    ),
                    'choices' => array(
                    ),
                    'default_value' => false,
                    'return_format' => 'value',
                    'multiple' => 0,
                    'allow_custom' => 0,
                    'search_placeholder' => '',
                    'allow_null' => 0,
                    'allow_in_bindings' => 1,
                    'ui' => 1,
                    'ajax' => 0,
                    'placeholder' => '',
                    'create_options' => 0,
                    'save_options' => 0,
                    'parent_repeater' => 'field_modularity_folder_browser_start_folders',
                ),
                1 => array(
                    'key' => 'field_modularity_folder_browser_folder',
                    'label' => __('Valda mappar', 'modularity-folder-browser'),
                    'name' => 'folder',
                    'aria-label' => '',
                    'type' => 'textarea',
                    'instructions' => __('Välj en eller flera mappar från den valda rotmappen.', 'modularity-folder-browser'),
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '100',
                        'class' => 'mod-file-browser-selected-folders-field',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'acfe_textarea_code' => 0,
                    'maxlength' => '',
                    'allow_in_bindings' => 1,
                    'rows' => 2,
                    'placeholder' => '',
                    'new_lines' => '',
                    'parent_repeater' => 'field_modularity_folder_browser_start_folders',
                ),
                2 => array(
                    'key' => 'field_modularity_folder_browser_initially_expanded',
                    'label' => __('Utfälld från början', 'modularity-folder-browser'),
                    'name' => 'initially_expanded',
                    'aria-label' => '',
                    'type' => 'true_false',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '100',
                        'class' => '',
                        'id' => '',
                    ),
                    'message' => '',
                    'default_value' => 0,
                    'allow_in_bindings' => 1,
                    'ui_on_text' => '',
                    'ui_off_text' => '',
                    'ui' => 1,
                    'parent_repeater' => 'field_modularity_folder_browser_start_folders',
                ),
            ),
        ),
        2 => array(
            'key' => 'field_modularity_folder_browser_show_file_type',
            'label' => __('Visa filtyp', 'modularity-folder-browser'),
            'name' => 'show_file_type',
            'aria-label' => '',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => false,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 1,
            'ui' => 1,
            'message' => '',
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
        3 => array(
            'key' => 'field_modularity_folder_browser_show_file_description',
            'label' => __('Visa filbeskrivning', 'modularity-folder-browser'),
            'name' => 'show_file_description',
            'aria-label' => '',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => false,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 1,
            'ui' => 1,
            'message' => '',
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
        4 => array(
            'key' => 'field_modularity_folder_browser_show_file_size',
            'label' => __('Visa filstorlek', 'modularity-folder-browser'),
            'name' => 'show_file_size',
            'aria-label' => '',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => false,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 1,
            'ui' => 1,
            'message' => '',
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
        5 => array(
            'key' => 'field_modularity_folder_browser_show_modified_date',
            'label' => __('Visa ändringsdatum', 'modularity-folder-browser'),
            'name' => 'show_modified_date',
            'aria-label' => '',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => false,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 1,
            'ui' => 1,
            'message' => '',
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
        6 => array(
            'key' => 'field_modularity_folder_browser_sort_order',
            'label' => __('Sorteringsordning', 'modularity-folder-browser'),
            'name' => 'sort_order',
            'aria-label' => '',
            'type' => 'select',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => false,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'name_asc' => __('Namn A-Ö', 'modularity-folder-browser'),
                'name_desc' => __('Namn Ö-A', 'modularity-folder-browser'),
                'date_desc' => __('Nyast först', 'modularity-folder-browser'),
                'date_asc' => __('Äldst först', 'modularity-folder-browser'),
                'type_asc' => __('Filtyp', 'modularity-folder-browser'),
            ),
            'default_value' => __('name_asc', 'modularity-folder-browser'),
            'return_format' => 'value',
            'ui' => 1,
            'multiple' => 0,
            'allow_null' => 0,
            'ajax' => 0,
            'placeholder' => '',
            'create_options' => 0,
            'save_options' => 0,
            'allow_custom' => 0,
            'search_placeholder' => '',
        ),
        7 => array(
            'key' => 'field_modularity_folder_browser_allowed_file_types',
            'label' => __('Åsidosätt tillåtna filtyper', 'modularity-folder-browser'),
            'name' => 'allowed_file_types_override',
            'aria-label' => '',
            'type' => 'checkbox',
            'instructions' => __('Valfri begränsning per modul. Om fältet lämnas tomt tillåts alla globalt konfigurerade filtyper.', 'modularity-folder-browser'),
            'required' => 0,
            'conditional_logic' => false,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
            ),
            'return_format' => 'value',
            'layout' => 'horizontal',
            'toggle' => 1,
            'default_value' => array(
            ),
            'allow_custom' => 0,
            'save_custom' => 0,
            'custom_choice_button_text' => 'Lägg till nytt val',
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'mod-folder-browser',
            ),
        ),
        1 => array(
            0 => array(
                'param' => 'block',
                'operator' => '==',
                'value' => 'acf/folder-browser',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'left',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
    'display_title' => '',
    'allow_ai_access' => false,
    'ai_description' => '',
    'acfe_autosync' => '',
    'acfe_form' => 0,
    'acfe_meta' => '',
    'acfe_note' => '',
));
}