<?php

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
        'key' => 'group_modularity_folder_browser_instance',
        'title' => __('Folder Browser Settings', 'modularity-folder-browser'),
        'fields' => array(
            array(
                'key' => 'field_modularity_folder_browser_start_folders',
                'label' => __('Start folders', 'modularity-folder-browser'),
                'name' => 'start_folders',
                'type' => 'repeater',
                'instructions' => __('Select one or more folders inside configured filesystem sources. Absolute paths are never stored.', 'modularity-folder-browser'),
                'required' => 1,
                'layout' => 'block',
                'button_label' => __('Add folder', 'modularity-folder-browser'),
                'min' => 1,
                'sub_fields' => array(
                    array(
                        'key' => 'field_modularity_folder_browser_source',
                        'label' => __('Source', 'modularity-folder-browser'),
                        'name' => 'source',
                        'type' => 'select',
                        'required' => 1,
                        'choices' => array(),
                        'return_format' => 'value',
                        'allow_null' => 0,
                        'ui' => 1,
                        'ajax' => 0,
                        'wrapper' => array(
                            'width' => '30',
                            'class' => 'mod-file-browser-source-field',
                        ),
                    ),
                    array(
                        'key' => 'field_modularity_folder_browser_folder',
                        'label' => __('Folder', 'modularity-folder-browser'),
                        'name' => 'folder',
                        'type' => 'text',
                        'instructions' => __('Relative path inside the selected source. Use the browser button or enter a path manually.', 'modularity-folder-browser'),
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => __('Leave empty to use the source root', 'modularity-folder-browser'),
                        'wrapper' => array(
                            'width' => '40',
                            'class' => 'mod-file-browser-folder-field',
                        ),
                    ),
                    array(
                        'key' => 'field_modularity_folder_browser_display_name',
                        'label' => __('Display name', 'modularity-folder-browser'),
                        'name' => 'display_name',
                        'type' => 'text',
                        'instructions' => __('Optional public name for this selected folder.', 'modularity-folder-browser'),
                        'required' => 0,
                        'wrapper' => array(
                            'width' => '20',
                        ),
                    ),
                    array(
                        'key' => 'field_modularity_folder_browser_initially_expanded',
                        'label' => __('Initially expanded', 'modularity-folder-browser'),
                        'name' => 'initially_expanded',
                        'type' => 'true_false',
                        'required' => 0,
                        'ui' => 1,
                        'wrapper' => array(
                            'width' => '10',
                        ),
                    ),
                ),
            ),
            array(
                'key' => 'field_modularity_folder_browser_show_file_type',
                'label' => __('Show file type', 'modularity-folder-browser'),
                'name' => 'show_file_type',
                'type' => 'true_false',
                'required' => 0,
                'default_value' => 1,
                'ui' => 1,
            ),
            array(
                'key' => 'field_modularity_folder_browser_show_file_size',
                'label' => __('Show file size', 'modularity-folder-browser'),
                'name' => 'show_file_size',
                'type' => 'true_false',
                'required' => 0,
                'default_value' => 1,
                'ui' => 1,
            ),
            array(
                'key' => 'field_modularity_folder_browser_show_modified_date',
                'label' => __('Show modified date', 'modularity-folder-browser'),
                'name' => 'show_modified_date',
                'type' => 'true_false',
                'required' => 0,
                'default_value' => 1,
                'ui' => 1,
            ),
            array(
                'key' => 'field_modularity_folder_browser_sort_order',
                'label' => __('Sort order', 'modularity-folder-browser'),
                'name' => 'sort_order',
                'type' => 'select',
                'required' => 0,
                'choices' => array(
                    'name_asc' => __('Name A-Z', 'modularity-folder-browser'),
                    'name_desc' => __('Name Z-A', 'modularity-folder-browser'),
                    'date_desc' => __('Newest first', 'modularity-folder-browser'),
                    'date_asc' => __('Oldest first', 'modularity-folder-browser'),
                    'type_asc' => __('File type', 'modularity-folder-browser'),
                ),
                'default_value' => 'name_asc',
                'return_format' => 'value',
                'ui' => 1,
            ),
            array(
                'key' => 'field_modularity_folder_browser_initial_state',
                'label' => __('Initial state', 'modularity-folder-browser'),
                'name' => 'initial_state',
                'type' => 'select',
                'required' => 0,
                'choices' => array(
                    'collapsed' => __('Collapsed', 'modularity-folder-browser'),
                    'expanded_first_level' => __('Expanded first level', 'modularity-folder-browser'),
                ),
                'default_value' => 'collapsed',
                'return_format' => 'value',
                'ui' => 1,
            ),
            array(
                'key' => 'field_modularity_folder_browser_allowed_file_types',
                'label' => __('Allowed file types override', 'modularity-folder-browser'),
                'name' => 'allowed_file_types_override',
                'type' => 'checkbox',
                'instructions' => __('Optional per-module restriction. Leaving this empty allows all globally configured file types.', 'modularity-folder-browser'),
                'required' => 0,
                'choices' => array(),
                'return_format' => 'value',
                'layout' => 'horizontal',
                'toggle' => 1,
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'mod-folder-browser',
                ),
            ),
            array(
                array(
                    'param' => 'block',
                    'operator' => '==',
                    'value' => 'acf/folder-browser',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'left',
        'instruction_placement' => 'label',
        'active' => true,
        'show_in_rest' => 0,
    ));
}
